# Generated by Django 5.0.1 on 2025-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_parkinglot_remove_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='allowed_vehicle_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='has_ev_charger',
            field=models.BooleanField(default=False),
        ),
    ]
