# Generated by Django 5.0.1 on 2025-12-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_profile_two_factor_enabled_profile_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdypuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
