# Generated by Django 5.0.1 on 2025-12-17 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0013_booking_check_in_qr_booking_check_out_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('invalid', 'Invalid'), ('expired', 'Expired')], default='valid', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_ticket', to='parking_app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
