# Generated by Django 5.0.1 on 2025-12-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0015_parkingslot_slot_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether SMS reminder has been sent'),
        ),
    ]
